### ISSUE TITLE
Make AuthorizeOperatorsItem Implementation

### ISSUE THREAD

**Issue by soonkuk** [ProtoconNet/mitum-sto#1]
## Expected Behavior
- Complete BaseAuthorizeOperatorsItem method
- Make AuthorizeOperatorsItem type
- Make bson and json encoding of AuthorizeOperatorsItem Implementaion
## Actual Behavior
- not implemented
## Specifications
  - commit; fc4ff1ece3cc7dabc83ade54066134e7131a9c80
  - os; macOS Monterey 12.6
  - go version; go1.19 darwin/arm64

**Comment by wyuinche** [comment]
@soonkuk Because authorize-operators items does not contain any field with multiple values, it is not necessary to implement items separated into "single" and "multi". I think I should implement items without distinction.

**Comment by socialinfratechdev** [comment]
@wyuinche Yes, you are right. I made expected behavior incorrectly.
And I also agree that single and multi item concept is no more needed.
I will update this issue. And also I update other issues about the single and multi items.
